# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Add.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_Phone(object):
    def setupUi(self, Add_Phone):
        Add_Phone.setObjectName("Add_Phone")
        Add_Phone.resize(702, 77)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Add_Phone.sizePolicy().hasHeightForWidth())
        Add_Phone.setSizePolicy(sizePolicy)
        Add_Phone.setMinimumSize(QtCore.QSize(702, 77))
        Add_Phone.setMaximumSize(QtCore.QSize(702, 77))
        self.centralwidget = QtWidgets.QWidget(Add_Phone)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 701, 76))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Id_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Id_Edit.setObjectName("Id_Edit")
        self.horizontalLayout.addWidget(self.Id_Edit)
        self.Surname_text = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Surname_text.setObjectName("Surname_text")
        self.horizontalLayout.addWidget(self.Surname_text)
        self.Name_Text = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Name_Text.setObjectName("Name_Text")
        self.horizontalLayout.addWidget(self.Name_Text)
        self.Adress_text = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Adress_text.setObjectName("Adress_text")
        self.horizontalLayout.addWidget(self.Adress_text)
        self.Phone_Namber = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Phone_Namber.setObjectName("Phone_Namber")
        self.horizontalLayout.addWidget(self.Phone_Namber)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Add_Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Add_Button.setObjectName("Add_Button")
        self.horizontalLayout_3.addWidget(self.Add_Button)
        self.Cancel_Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Cancel_Button.setObjectName("Cancel_Button")
        self.horizontalLayout_3.addWidget(self.Cancel_Button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        Add_Phone.setCentralWidget(self.centralwidget)

        self.retranslateUi(Add_Phone)
        QtCore.QMetaObject.connectSlotsByName(Add_Phone)

    def retranslateUi(self, Add_Phone):
        _translate = QtCore.QCoreApplication.translate
        Add_Phone.setWindowTitle(_translate("Add_Phone", "Добавить в телефонную книгу"))
        self.label_5.setText(_translate("Add_Phone", "Номер записи"))
        self.label_4.setText(_translate("Add_Phone", "Фамилия"))
        self.label_3.setText(_translate("Add_Phone", "Имя"))
        self.label_2.setText(_translate("Add_Phone", "Адрес"))
        self.label.setText(_translate("Add_Phone", "Номер телефона"))
        self.Add_Button.setText(_translate("Add_Phone", "Добавить"))
        self.Cancel_Button.setText(_translate("Add_Phone", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Add_Phone = QtWidgets.QMainWindow()
    ui = Ui_Add_Phone()
    ui.setupUi(Add_Phone)
    Add_Phone.show()
    sys.exit(app.exec_())
