# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Delete.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Delete_Window(object):
    def setupUi(self, Delete_Window):
        Delete_Window.setObjectName("Delete_Window")
        Delete_Window.resize(271, 52)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Delete_Window.sizePolicy().hasHeightForWidth())
        Delete_Window.setSizePolicy(sizePolicy)
        Delete_Window.setMinimumSize(QtCore.QSize(250, 52))
        Delete_Window.setMaximumSize(QtCore.QSize(271, 52))
        self.centralwidget = QtWidgets.QWidget(Delete_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 271, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Ok = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Ok.setObjectName("Ok")
        self.horizontalLayout_2.addWidget(self.Ok)
        self.Cancel = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Cancel.setObjectName("Cancel")
        self.horizontalLayout_2.addWidget(self.Cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        Delete_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Delete_Window)
        QtCore.QMetaObject.connectSlotsByName(Delete_Window)

    def retranslateUi(self, Delete_Window):
        _translate = QtCore.QCoreApplication.translate
        Delete_Window.setWindowTitle(_translate("Delete_Window", "Удалить из телефонной книги"))
        self.label.setText(_translate("Delete_Window", "Введте номер строки для удаления:"))
        self.Ok.setText(_translate("Delete_Window", "Ok"))
        self.Cancel.setText(_translate("Delete_Window", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Delete_Window = QtWidgets.QMainWindow()
    ui = Ui_Delete_Window()
    ui.setupUi(Delete_Window)
    Delete_Window.show()
    sys.exit(app.exec_())
