# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(511, 401)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(511, 401))
        MainWindow.setMaximumSize(QtCore.QSize(511, 401))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 511, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Add_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Add_Button.setObjectName("Add_Button")
        self.horizontalLayout.addWidget(self.Add_Button)
        self.Delete_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Delete_Button.setObjectName("Delete_Button")
        self.horizontalLayout.addWidget(self.Delete_Button)
        self.Update_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Update_Button.setObjectName("Update_Button")
        self.horizontalLayout.addWidget(self.Update_Button)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 30, 511, 371))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Main_Table = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.Main_Table.setObjectName("Main_Table")
        self.Main_Table.setColumnCount(5)
        self.Main_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Main_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Main_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Main_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Main_Table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Main_Table.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.Main_Table)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Телефонная книга"))
        self.Add_Button.setText(_translate("MainWindow", "Добавить"))
        self.Delete_Button.setText(_translate("MainWindow", "Удалить"))
        self.Update_Button.setText(_translate("MainWindow", "Сохранить"))
        item = self.Main_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Номер записи"))
        item = self.Main_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Фамилия"))
        item = self.Main_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Имя"))
        item = self.Main_Table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Номер телефона"))
        item = self.Main_Table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Адрес"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
